name: Javascript tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
      - name: Test wasm-pack was installed
        run: wasm-pack --version
      
      - name: Test wasm-bindgen was installed
        run: wasm-bindgen --version

      - run: npm install
      - run: npm run build
      - run: npm run test

