name : WASM bindgen tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: cd /home/runner/work/verkle-cryptography-wasm/verkle-cryptography-wasm/src && wasm-pack test --headless --chrome
      - run: cd /home/runner/work/verkle-cryptography-wasm/verkle-cryptography-wasm/src && wasm-pack test --headless --firefox
